pipeline {
  agent any

  stages {
    stage('Prepare') {
      steps {
        // ensure folder exists (no error if already present)
        sh 'mkdir -p services/data-ingestor || true'
      }
    }

    stage('Generate dashboard') {
      steps {
        // create a simple HTML dashboard and include build info
        sh '''
cat > dashboard.html <<HTML
<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8"/>
  <meta name="viewport" content="width=device-width,initial-scale=1"/>
  <title>SmartFarm - Build Dashboard</title>
  <style>
    body{font-family:system-ui,Arial;margin:28px}
    header{margin-bottom:18px}
    .meta{font-size:0.95rem;color:#444}
    pre{background:#f6f6f6;padding:12px;border-radius:6px;overflow:auto}
    .box{border:1px solid #eee;padding:12px;border-radius:8px;margin-top:12px}
  </style>
</head>
<body>
  <header>
    <h1>SmartFarm — Build Dashboard</h1>
    <div class="meta">Job: ${JOB_NAME}  •  Build: ${BUILD_NUMBER}  •  URL: ${BUILD_URL}</div>
  </header>

  <section class="box">
    <h3>Repository</h3>
    <div><a href="https://github.com/jaii31/SmartFarm">https://github.com/jaii31/SmartFarm</a></div>
  </section>

  <section class="box">
    <h3>Latest Console Snippet</h3>
    <pre>$( (test -f ./console_snippet.txt && cat ./console_snippet.txt) || echo "Console snippet not saved. Check build console in Jenkins.")</pre>
  </section>

  <section class="box">
    <h3>Notes</h3>
    <ul>
      <li>Generated by Jenkinsfile (no Docker required on agent).</li>
      <li>If you want full logs inside the artifact, enable steps that write logs to files (example: console_snippet.txt).</li>
    </ul>
  </section>
</body>
</html>
HTML
'''
      }
    }

    stage('Archive artifact') {
      steps {
        archiveArtifacts artifacts: 'dashboard.html', fingerprint: true
      }
    }
  }

  post {
    success { echo "Pipeline finished: success" }
    failure { echo "Pipeline finished: failed" }
  }
}
